name: Build binaries

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: make

      - run: |
          chmod +x ./unpackbootimg
          chmod +x ./mkbootimg

      - name: Upload binary - unpackbootimg
        uses: actions/upload-artifact@v3
        with:
          name: unpackbootimg
          path: |
            ./unpackbootimg

      - name: Upload binary - mkbootimg
        uses: actions/upload-artifact@v3
        with:
          name: mkbootimg
          path: |
            ./mkbootimg
